# Generated by Django 4.2.7 on 2026-04-20 13:33

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff Member'), ('student', 'Student'), ('parent', 'Parent/Guardian')], default='student', help_text='User role for RBAC', max_length=20)),
                ('biometric_hash', models.TextField(blank=True, help_text='Encrypted fingerprint template hash', null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='Primary contact for SMS notifications', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.BooleanField(default=True)),
                ('notification_prefs', models.JSONField(blank=True, default=dict, help_text='{absence_alerts: bool, grade_updates: bool, general_announcements: bool}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Optional portal access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent/Guardian',
                'verbose_name_plural': 'Parents/Guardians',
                'db_table': 'parents',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_number', models.CharField(help_text='Unique student ID number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('grade_level', models.CharField(blank=True, max_length=20, null=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_records', models.JSONField(blank=True, default=dict, help_text='JSON field for GPA, credits, academic standing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(help_text='Unique staff ID number', max_length=50, unique=True)),
                ('position', models.CharField(choices=[('teacher', 'Teacher'), ('administrator', 'Administrator'), ('support', 'Support Staff'), ('principal', 'Principal'), ('hr', 'HR Manager')], max_length=20)),
                ('department', models.CharField(choices=[('academics', 'Academics'), ('administration', 'Administration'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('it', 'IT'), ('maintenance', 'Maintenance')], max_length=20)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('shift_start_time', models.TimeField(default='08:00', help_text='Shift start time (HH:MM)')),
                ('shift_end_time', models.TimeField(default='17:00', help_text='Shift end time (HH:MM)')),
                ('late_threshold_minutes', models.IntegerField(default=15, help_text='Minutes after shift start to be considered late')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for emergency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='core.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='core.student')),
            ],
            options={
                'verbose_name': 'Parent-Student Link',
                'verbose_name_plural': 'Parent-Student Links',
                'db_table': 'parent_student_links',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('att_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('in', 'Clock In'), ('out', 'Clock Out')], help_text='Clock in or out', max_length=10)),
                ('method', models.CharField(choices=[('biometric', 'Biometric/Fingerprint'), ('manual', 'Manual Entry'), ('card', 'Card/RFID')], default='biometric', max_length=20)),
                ('is_late', models.BooleanField(default=False, help_text='True if clock-in is past shift start + threshold')),
                ('late_minutes', models.IntegerField(blank=True, help_text='Number of minutes late', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('biometric_match_score', models.FloatField(blank=True, help_text='Fingerprint match confidence score (0-100)', null=True)),
                ('device_id', models.CharField(blank=True, help_text='Biometric device identifier', max_length=100, null=True)),
                ('location', models.CharField(blank=True, help_text='GPS coordinates or location name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, db_column='staff_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.staff')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified manual entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('student_att_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='academics.course')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance Records',
                'db_table': 'student_attendance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student'], name='student_att_student_22319e_idx'), models.Index(fields=['date'], name='student_att_date_1ee40f_idx'), models.Index(fields=['status'], name='student_att_status_9239ff_idx'), models.Index(fields=['parent_notified'], name='student_att_parent__8ae2b1_idx')],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number'], name='students_student_fa2474_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_status_3ac771_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade_level'], name='students_grade_l_f9abe0_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_number'], name='staff_staff_n_8a8c46_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department'], name='staff_departm_db298c_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['position'], name='staff_positio_79ee03_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active'], name='staff_is_acti_e9a75c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentlink',
            unique_together={('parent', 'student')},
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['phone'], name='parents_phone_b7d597_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['emergency_contact'], name='parents_emergen_9dcf28_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user'], name='attendance_user_id_1ea673_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['timestamp'], name='attendance_timesta_d0ec2c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_late'], name='attendance_is_late_0da71f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance_status_a068a7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
    ]
