# Generated by Django 4.2.7 on 2026-04-27 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_department_gradecomponent_semester_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="e.g. GRADE_UPDATED, LEAVE_APPROVED", max_length=100
                    ),
                ),
                (
                    "target_table",
                    models.CharField(
                        help_text="Which table was affected", max_length=100
                    ),
                ),
                ("target_id", models.UUIDField(help_text="Which record was affected")),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="State before change", null=True
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="State after change", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        help_text="IP address of the actor",
                        max_length=45,
                        null=True,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was performed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_log",
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "token_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="Hashed refresh token for security",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True,
                        help_text="Browser/device identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        help_text="IPv4 or IPv6 address",
                        max_length=45,
                        null=True,
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When token was issued"
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="When token expires")),
                (
                    "revoked",
                    models.BooleanField(default=False, help_text="Set true on logout"),
                ),
            ],
            options={
                "verbose_name": "Refresh Token",
                "verbose_name_plural": "Refresh Tokens",
                "db_table": "refresh_tokens",
            },
        ),
        migrations.RemoveIndex(
            model_name="studentattendance",
            name="student_att_parent__8ae2b1_idx",
        ),
        migrations.RenameIndex(
            model_name="staff",
            new_name="staff_departm_a70fd6_idx",
            old_name="staff_departm_db298c_idx",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="late_threshold_minutes",
        ),
        migrations.RemoveField(
            model_name="student",
            name="academic_records",
        ),
        migrations.RemoveField(
            model_name="student",
            name="graduation_date",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="marked_at",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="notification_sent_at",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="parent_notified",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="student_att_id",
        ),
        migrations.AddField(
            model_name="staff",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                ],
                default="full_time",
                help_text="Employment type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.CharField(
                default="", help_text="Academic year e.g. 2024/2025", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's department/faculty",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="programme",
            field=models.CharField(
                blank=True, help_text="Programme of study", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="notified_parent",
            field=models.BooleanField(
                default=False, help_text="Flipped after SMS sent"
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="record_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                db_column="semester_id",
                help_text="Semester FK",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_attendance",
                to="academics.semester",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.ForeignKey(
                help_text="Department FK",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_members",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="hire_date",
            field=models.DateField(help_text="Date of hire"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.CharField(help_text="Staff position/title", max_length=150),
        ),
        migrations.AlterField(
            model_name="staff",
            name="salary",
            field=models.TextField(
                blank=True, help_text="Encrypted salary (AES-256)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="shift_end_time",
            field=models.TimeField(
                blank=True, help_text="Shift end time (HH:MM)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="shift_start_time",
            field=models.TimeField(
                blank=True, help_text="Shift start time (HH:MM)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="termination_date",
            field=models.DateField(
                blank=True, help_text="Date of termination (if applicable)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(
                blank=True, help_text="Student's address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Student's date of birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Date of enrollment"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(
                help_text="First name (from user profile)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade_level",
            field=models.CharField(
                blank=True,
                help_text="Grade level (for frontend compatibility)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(
                help_text="Last name (from user profile)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(
                blank=True,
                help_text="Section (for frontend compatibility)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("graduated", "Graduated"),
                    ("suspended", "Suspended"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="active",
                help_text="Student status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="course",
            field=models.ForeignKey(
                help_text="Course FK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attendance",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="date",
            field=models.DateField(help_text="Attendance date"),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="marked_by",
            field=models.ForeignKey(
                help_text="Staff who marked attendance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendance",
                to="core.staff",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                ],
                help_text="Attendance status",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                help_text="Student FK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="core.student",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="biometric_hash",
            field=models.TextField(
                blank=True,
                help_text="Encrypted fingerprint template hash (AES-256)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["course"], name="student_att_course__cd680c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["semester"], name="student_att_semeste_a90fab_idx"
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this token",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                help_text="User who performed the action",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["user"], name="refresh_tok_user_id_46676d_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["token_hash"], name="refresh_tok_token_h_2fa7c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["expires_at"], name="refresh_tok_expires_a128d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["actor"], name="audit_log_actor_i_8c3cd6_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_table", "target_id"],
                name="audit_log_target__96fd00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["performed_at"], name="audit_log_perform_3eb331_idx"
            ),
        ),
    ]
