# Generated by Django 4.2.13 on 2026-05-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog_refreshtoken_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="parentstudentlink",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="parentstudentlink",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="parentstudentlink",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentattendance",
            name="notified_parent",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("staff", "Staff Member"),
                    ("student", "Student"),
                ],
                default="student",
                help_text="User role for RBAC",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Parent",
        ),
        migrations.DeleteModel(
            name="ParentStudentLink",
        ),
    ]
