# Generated by Django 4.2.13 on 2026-05-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_attendance_session_system_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="face_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="webauthn_challenge",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="webauthn_challenge_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="webauthn_credential_id",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="webauthn_public_key",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="webauthn_sign_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="biometric_hash",
            field=models.TextField(blank=True, null=True),
        ),
    ]
