# Generated by Django 4.2.13 on 2026-05-30 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_biometric_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentToken",
            fields=[
                (
                    "token_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "enrollment_type",
                    models.CharField(
                        choices=[
                            ("fingerprint", "Fingerprint (WebAuthn)"),
                            ("face", "Face Recognition"),
                            ("both", "Fingerprint + Face"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_enrollment_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "enrollment_tokens",
                "ordering": ["-expires_at"],
            },
        ),
    ]
