# Generated by Django 4.2.13 on 2026-06-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_course_class_group"),
        ("core", "0010_classgroup_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department FK",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_members",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.CharField(
                blank=True, help_text="Staff position/title", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="staff_number",
            field=models.CharField(
                blank=True,
                help_text="Unique staff ID number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("it_technician", "IT Technician"),
                    ("staff", "Teacher"),
                    ("student", "Student"),
                ],
                default="student",
                help_text="User role for RBAC",
                max_length=20,
            ),
        ),
    ]
