# Generated by Django 4.2.7 on 2026-04-20 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAttendanceSummary",
            fields=[
                (
                    "summary_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("total_work_days", models.IntegerField()),
                ("days_present", models.IntegerField()),
                ("days_absent", models.IntegerField()),
                ("days_late", models.IntegerField()),
                ("total_late_minutes", models.IntegerField(default=0)),
                ("average_late_minutes", models.FloatField(default=0.0)),
                ("attendance_percentage", models.FloatField()),
                ("punctuality_percentage", models.FloatField()),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Attendance Summary",
                "verbose_name_plural": "Staff Attendance Summaries",
                "db_table": "staff_attendance_summaries",
                "unique_together": {("staff", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "balance_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField()),
                ("annual_entitlement", models.IntegerField(default=21)),
                ("annual_used", models.IntegerField(default=0)),
                ("annual_remaining", models.IntegerField(default=21)),
                ("sick_entitlement", models.IntegerField(default=10)),
                ("sick_used", models.IntegerField(default=0)),
                ("sick_remaining", models.IntegerField(default=10)),
                ("emergency_used", models.IntegerField(default=0)),
                ("unpaid_used", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "db_table": "leave_balances",
                "unique_together": {("staff", "year")},
            },
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "leave_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("emergency", "Emergency Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("unpaid", "Unpaid Leave"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_days", models.IntegerField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("attachment_url", models.URLField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "leaves",
                "ordering": ["-applied_at"],
                "indexes": [
                    models.Index(fields=["staff"], name="leaves_staff_i_16e279_idx"),
                    models.Index(fields=["status"], name="leaves_status_1a86dc_idx"),
                    models.Index(
                        fields=["start_date"], name="leaves_start_d_190f6a_idx"
                    ),
                ],
            },
        ),
    ]
