# Generated by Django 4.2.7 on 2026-04-20 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('metric_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['name'], name='system_metr_name_15dfc1_idx'), models.Index(fields=['category'], name='system_metr_categor_03b93e_idx'), models.Index(fields=['timestamp'], name='system_metr_timesta_206ca6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('attendance', 'Attendance Report'), ('grades', 'Grades Report'), ('enrollment', 'Enrollment Report'), ('staff_performance', 'Staff Performance Report'), ('student_performance', 'Student Performance Report'), ('financial', 'Financial Report'), ('attendance_summary', 'Attendance Summary'), ('leave_summary', 'Leave Summary'), ('course_statistics', 'Course Statistics'), ('user_activity', 'User Activity Report'), ('custom', 'Custom Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Report parameters for scheduled generation')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'report_schedules',
                'indexes': [models.Index(fields=['frequency'], name='report_sche_frequen_825450_idx'), models.Index(fields=['is_active'], name='report_sche_is_acti_12ab8c_idx'), models.Index(fields=['next_run'], name='report_sche_next_ru_270fdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('attendance', 'Attendance Report'), ('grades', 'Grades Report'), ('enrollment', 'Enrollment Report'), ('staff_performance', 'Staff Performance Report'), ('student_performance', 'Student Performance Report'), ('financial', 'Financial Report'), ('attendance_summary', 'Attendance Summary'), ('leave_summary', 'Leave Summary'), ('course_statistics', 'Course Statistics'), ('user_activity', 'User Activity Report'), ('custom', 'Custom Report')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF Document'), ('excel', 'Excel Spreadsheet'), ('csv', 'CSV File'), ('json', 'JSON Data')], default='pdf', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Report generation parameters (date range, filters, etc.)')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Report data in JSON format')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type'], name='reports_report__ff8b25_idx'), models.Index(fields=['status'], name='reports_status_e83c1d_idx'), models.Index(fields=['generated_by'], name='reports_generat_4a23eb_idx'), models.Index(fields=['created_at'], name='reports_created_c5f642_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('print', 'Print'), ('approve', 'Approve'), ('reject', 'Reject'), ('archive', 'Archive')], max_length=20)),
                ('object_type', models.CharField(help_text="Type of object affected (e.g., 'User', 'Course', 'Grade')", max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=200, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['object_type'], name='audit_logs_object__69dfc3_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
    ]
