# Generated by Django 4.2.7 on 2026-04-27 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
