# Generated by Django 4.2.7 on 2026-04-20 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcementreadreceipt",
            name="announcement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_receipts",
                to="communication.announcement",
            ),
        ),
        migrations.AddField(
            model_name="announcementreadreceipt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient"], name="notificatio_recipie_1dd18d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_read"], name="notificatio_is_read_3f8c44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_19df93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_e4c995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcementreadreceipt",
            index=models.Index(fields=["user"], name="announcemen_user_id_bf156e_idx"),
        ),
        migrations.AddIndex(
            model_name="announcementreadreceipt",
            index=models.Index(
                fields=["read_at"], name="announcemen_read_at_261406_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="announcementreadreceipt",
            unique_together={("announcement", "user")},
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["target_role"], name="announcemen_target__835227_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["priority"], name="announcemen_priorit_370592_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["is_active"], name="announcemen_is_acti_8058e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["publish_at"], name="announcemen_publish_a885af_idx"
            ),
        ),
    ]
