# Generated by Django 4.2.7 on 2026-04-27 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="announcemen_priorit_370592_idx",
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="announcemen_publish_a885af_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_is_read_3f8c44_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_notific_19df93_idx",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="expire_at",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="is_pinned",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="publish_at",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="views_count",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="email_sent",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="read_at",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_object_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_object_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sms_sent",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
        migrations.AddField(
            model_name="announcement",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Expiration date", null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="body",
            field=models.TextField(default="", help_text="Notification body/content"),
        ),
        migrations.AddField(
            model_name="notification",
            name="notif_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient_phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number for parent SMS alerts",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_id",
            field=models.UUIDField(
                blank=True, help_text="FK to source record", null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_table",
            field=models.CharField(
                blank=True,
                help_text="Source context e.g. StudentAttendance",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, help_text="When the notification was sent", null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Delivery status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Subject for email type",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("in_app", "In-App"), ("email", "Email"), ("sms", "SMS")],
                default="in_app",
                help_text="Notification type",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                help_text="User who created the announcement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(help_text="Announcement content"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Active status"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="target_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administrators"),
                    ("staff", "Staff Members"),
                    ("student", "Students"),
                    ("parent", "Parents/Guardians"),
                ],
                help_text="null = everyone",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(help_text="Announcement title", max_length=255),
        ),
        migrations.AlterField(
            model_name="announcementreadreceipt",
            name="announcement",
            field=models.ForeignKey(
                help_text="The announcement that was read",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_receipts",
                to="communication.announcement",
            ),
        ),
        migrations.AlterField(
            model_name="announcementreadreceipt",
            name="read_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the announcement was read"
            ),
        ),
        migrations.AlterField(
            model_name="announcementreadreceipt",
            name="user",
            field=models.ForeignKey(
                help_text="User who read the announcement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="User recipient (null for SMS to parents)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["created_at"], name="announcemen_created_cc79cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status"], name="notificatio_status_fce6f5_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
        ),
    ]
