# Generated by Django 4.2.13 on 2026-05-24 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communication", "0003_alter_announcement_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="recipient_phone",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="target_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administrators"),
                    ("staff", "Staff Members"),
                    ("student", "Students"),
                ],
                help_text="null = everyone",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Notification recipient user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
