# Generated by Django 4.2.7 on 2026-04-20 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "assign_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("quiz", "Quiz"),
                            ("exam", "Exam"),
                            ("project", "Project"),
                            ("lab", "Laboratory"),
                            ("essay", "Essay"),
                        ],
                        default="homework",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("attachment_url", models.URLField(blank=True, null=True)),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "PDF Document"),
                            ("doc", "Word Document"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("link", "External Link"),
                            ("code", "Code File"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("allow_late_submission", models.BooleanField(default=False)),
                (
                    "late_penalty_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage deduction per day late",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignments",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        help_text="Unique course identifier (e.g., CS101)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("credits", models.IntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{day: string, start_time: HH:MM, end_time: HH:MM, room: string}",
                    ),
                ),
                (
                    "prerequisites",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of prerequisite course IDs",
                    ),
                ),
                ("semester", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "academic_year",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("max_students", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "enrollment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("semester", models.CharField(max_length=20)),
                ("academic_year", models.CharField(max_length=10)),
                ("midterm_grade", models.TextField(blank=True, null=True)),
                ("final_grade", models.TextField(blank=True, null=True)),
                ("letter_grade", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollments",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "sub_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("late", "Late"),
                            ("resubmitted", "Resubmitted"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("content_text", models.TextField(blank=True, null=True)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                ("grade", models.TextField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plagiarism_score",
                    models.FloatField(
                        blank=True,
                        help_text="Plagiarism detection score (0-100)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="academics.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission",
                "verbose_name_plural": "Submissions",
                "db_table": "submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
