# Generated by Django 4.2.7 on 2026-04-27 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Department name", max_length=150, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Department code e.g. CS, BUS",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Department description", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active status"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="GradeComponent",
            fields=[
                (
                    "component_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. CAT 1, Final Exam", max_length=100
                    ),
                ),
                (
                    "weight_percent",
                    models.FloatField(
                        help_text="Weight percentage (must sum to 100 per course)"
                    ),
                ),
                (
                    "max_score",
                    models.FloatField(
                        default=100.0, help_text="Maximum possible score"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Due date for this component", null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cat", "Continuous Assessment Test"),
                            ("exam", "Examination"),
                            ("assignment", "Assignment"),
                            ("project", "Project"),
                        ],
                        help_text="Type of grade component",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Component",
                "verbose_name_plural": "Grade Components",
                "db_table": "grade_components",
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "semester_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Semester 1 – 2025", max_length=50, unique=True
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g. 2024/2025", max_length=20),
                ),
                ("start_date", models.DateField(help_text="Semester start date")),
                ("end_date", models.DateField(help_text="Semester end date")),
                (
                    "enrollment_open",
                    models.DateField(help_text="When students can enroll"),
                ),
                ("enrollment_close", models.DateField(help_text="Enrollment deadline")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="upcoming",
                        help_text="Semester status",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
                "db_table": "semesters",
            },
        ),
        migrations.CreateModel(
            name="StudentGradeComponent",
            fields=[
                (
                    "sgc_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Student's score (null until graded)",
                        null=True,
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, help_text="When the grade was assigned", null=True
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Additional remarks on the grade",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Grade Component",
                "verbose_name_plural": "Student Grade Components",
                "db_table": "student_grade_components",
            },
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="courses_instruc_77fba4_idx",
        ),
        migrations.RemoveField(
            model_name="course",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="course",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
        migrations.RemoveField(
            model_name="course",
            name="prerequisites",
        ),
        migrations.RemoveField(
            model_name="course",
            name="schedule",
        ),
        migrations.AddField(
            model_name="course",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                db_column="staff_id",
                help_text="Primary lecturer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_teaching",
                to="core.staff",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When student enrolled"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="grade_letter",
            field=models.CharField(
                blank=True, help_text="e.g. A, B+", max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(help_text="e.g. CS301", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.IntegerField(default=3, help_text="Credit hours"),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True, help_text="Course description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="max_students",
            field=models.IntegerField(default=30, help_text="Maximum enrollment"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(help_text="Course name", max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                ],
                default="active",
                help_text="Course status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                help_text="Course FK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="final_grade",
            field=models.FloatField(
                blank=True, help_text="Computed from GradeComponents", null=True
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("dropped", "Dropped"),
                    ("completed", "Completed"),
                ],
                default="active",
                help_text="Enrollment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="Student FK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="core.student",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.TextField(
                blank=True, help_text="Encrypted grade (AES-256)", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["staff"], name="courses_staff_i_35013a_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["semester"], name="enrollments_semeste_f42de3_idx"
            ),
        ),
        migrations.AddField(
            model_name="studentgradecomponent",
            name="component",
            field=models.ForeignKey(
                help_text="The grade component being scored",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_grades",
                to="academics.gradecomponent",
            ),
        ),
        migrations.AddField(
            model_name="studentgradecomponent",
            name="enrollment",
            field=models.ForeignKey(
                help_text="Student's enrollment in the course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_components",
                to="academics.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="studentgradecomponent",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who graded this",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_components",
                to="core.staff",
            ),
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["academic_year"], name="semesters_academi_e17a7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(fields=["status"], name="semesters_status_abd5d2_idx"),
        ),
        migrations.AddIndex(
            model_name="semester",
            index=models.Index(
                fields=["start_date", "end_date"], name="semesters_start_d_6bb54f_idx"
            ),
        ),
        migrations.AddField(
            model_name="gradecomponent",
            name="course",
            field=models.ForeignKey(
                help_text="Course this component belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_components",
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="hod",
            field=models.ForeignKey(
                blank=True,
                help_text="Head of Department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="core.staff",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                help_text="Department FK",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                db_column="semester_id",
                help_text="Semester FK",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="academics.semester",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="semester",
            field=models.ForeignKey(
                db_column="semester_id",
                help_text="Semester FK",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="academics.semester",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course", "semester")},
        ),
        migrations.AddIndex(
            model_name="studentgradecomponent",
            index=models.Index(
                fields=["enrollment"], name="student_gra_enrollm_4094af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentgradecomponent",
            index=models.Index(
                fields=["component"], name="student_gra_compone_cd4f77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentgradecomponent",
            unique_together={("enrollment", "component")},
        ),
        migrations.AddIndex(
            model_name="gradecomponent",
            index=models.Index(
                fields=["course"], name="grade_compo_course__61d23e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gradecomponent",
            index=models.Index(fields=["type"], name="grade_compo_type_c5434d_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="departments_code_9f933a_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active"], name="departments_is_acti_a777bd_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="enrollment_date",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="letter_grade",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="midterm_grade",
        ),
    ]
