# Generated by Django 4.2.13 on 2026-05-24 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alter_parentstudentlink_unique_together_and_more"),
        ("academics", "0003_department_gradecomponent_semester_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "timetable_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_group",
                    models.CharField(help_text="e.g. Form 3A, Form 4B", max_length=50),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        help_text="Day of the week",
                        max_length=10,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Period start time e.g. 08:00"),
                ),
                ("end_time", models.TimeField(help_text="Period end time e.g. 09:00")),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        help_text="Classroom or lab",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Semester this slot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="academics.semester",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject for this slot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="academics.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher taking this slot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_slots",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Slot",
                "verbose_name_plural": "Timetable Slots",
                "db_table": "timetable",
                "indexes": [
                    models.Index(
                        fields=["semester"], name="timetable_semeste_1199a1_idx"
                    ),
                    models.Index(
                        fields=["class_group"], name="timetable_class_g_cad977_idx"
                    ),
                    models.Index(
                        fields=["teacher"], name="timetable_teacher_216925_idx"
                    ),
                    models.Index(
                        fields=["day_of_week"], name="timetable_day_of__f3d59b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubjectTeacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary teacher for this subject (for display and attendance marking)",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Admin who made the assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject being taught",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_teachers",
                        to="academics.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="The teacher assigned to this subject",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="core.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Teacher",
                "verbose_name_plural": "Subject Teachers",
                "db_table": "subject_teachers",
                "indexes": [
                    models.Index(
                        fields=["subject"], name="subject_tea_subject_0dd304_idx"
                    ),
                    models.Index(
                        fields=["teacher"], name="subject_tea_teacher_3edb28_idx"
                    ),
                ],
                "unique_together": {("subject", "teacher")},
            },
        ),
        migrations.CreateModel(
            name="ResultCard",
            fields=[
                (
                    "result_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cat1_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CAT 1 score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "cat2_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CAT 2 score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final exam score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weighted total (computed)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A — Excellent (80-100)"),
                            ("B", "B — Good (70-79)"),
                            ("C", "C — Average (60-69)"),
                            ("D", "D — Below Average (50-59)"),
                            ("E", "E — Poor (40-49)"),
                            ("F", "F — Fail (0-39)"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "computed_by",
                    models.ForeignKey(
                        help_text="Teacher who computed/approved this result",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="computed_results",
                        to="core.staff",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Semester/term",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_cards",
                        to="academics.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_cards",
                        to="core.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject/course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_cards",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Card",
                "verbose_name_plural": "Result Cards",
                "db_table": "result_cards",
                "indexes": [
                    models.Index(
                        fields=["student"], name="result_card_student_fbd154_idx"
                    ),
                    models.Index(
                        fields=["semester"], name="result_card_semeste_558701_idx"
                    ),
                    models.Index(
                        fields=["subject"], name="result_card_subject_83fee7_idx"
                    ),
                ],
                "unique_together": {("student", "subject", "semester")},
            },
        ),
    ]
