# Generated by Django 4.2.13 on 2026-05-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_timetable_subjectteacher_resultcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department FK (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="academics.department",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                db_column="semester_id",
                help_text="Semester FK (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="academics.semester",
            ),
        ),
    ]
