# Generated by Django 4.2.7 on 2026-08-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0006_course_class_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultcard",
            name="batch_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Groups result cards created/updated together in one bulk import, for draft review",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resultcard",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resultcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft — not visible to student"),
                    ("published", "Published — visible to student"),
                ],
                db_index=True,
                default="published",
                help_text="Draft results are hidden from the student until published",
                max_length=10,
            ),
        ),
    ]
